#!/bin/sh
brightness=`grep "background" ~/.config/termite/config`
if [ "$brightness" == "background = #fdf6e3" ]
then
  echo black > ~/scripts/var/bgcolor
  echo "#ab4642" > ~/scripts/var/fgcolor
  echo "#181818" > ~/scripts/var/bgcolorClock
  ~/scripts/allxtermcontrol --bg 'rgb:1800/1800/1800'
  ~/scripts/allxtermcontrol --fg 'rgb:AB00/4600/4200'
  sed -i "s/background = .*/background = #181818/" ~/.config/termite/config
  sed -i "s/foreground = .*/foreground = #ab4642/" ~/.config/termite/config
  sed -i "s/set recolor-lightcolor .*/set recolor-lightcolor \"#181818\"/" ~/.config/zathura/zathurarc
  sed -i "s/set recolor-darkcolor .*/set recolor-darkcolor \"#ab4642\"/" ~/.config/zathura/zathurarc
fi
