#!/bin/sh
brightness=`grep "background" ~/.config/termite/config`
if [ "$brightness" == "background = #181818" ]
then
  feh --bg-scale ~/scripts/var/white.png
  echo white > ~/scripts/var/bgcolor
  echo "#839496" > ~/scripts/var/fgcolor
  echo "#fdf6e3" > ~/scripts/var/bgcolorClock
  ./allxtermcontrol  '#839496' '#fdf6e3'
  sed -i "s/background = .*/background = #fdf6e3/" ~/.config/termite/config
  sed -i "s/foreground = .*/foreground = #839496/" ~/.config/termite/config
  sed -i "s/set recolor-lightcolor .*/set recolor-lightcolor \"#fdf6e3\"/" ~/.config/zathura/zathurarc
  sed -i "s/set recolor-darkcolor .*/set recolor-darkcolor \"#839496\"/" ~/.config/zathura/zathurarc
fi
