#!/bin/sh
brightness=$(grep "background" ~/.config/termite/config | cut -d' ' -f3)
if [ "$brightness" != "#181818" ]
then
  feh --bg-scale ~/scripts/var/black.png
  echo black > ~/scripts/var/bgcolor
  echo "#ab4642" > ~/scripts/var/fgcolor
  echo "#181818" > ~/scripts/var/bgcolorClock
  ~/scripts/allxtermcontrol '#AB4642' '#181818' 
  sed -i "s/background = .*/background = #181818/" ~/.config/termite/config
  sed -i "s/foreground = .*/foreground = #ab4642/" ~/.config/termite/config
  sed -i "s/set recolor-lightcolor .*/set recolor-lightcolor \"#181818\"/" ~/.config/zathura/zathurarc
  sed -i "s/set recolor-darkcolor .*/set recolor-darkcolor \"#ab4642\"/" ~/.config/zathura/zathurarc
fi
