#!/bin/sh
fgcolor=$(cat ~/scripts/var/fgcolor)
bgcolor=$(cat ~/scripts/var/bgcolorClock)
osdx='osd_cat -d 3 -O 2 -u '$bgcolor' -A center -l 3 -p bottom -o 60 -c '$fgcolor' -f '-*-terminus-*-*-*-*-*-280-*-*-*-*-*-*''
printf  "$(date "+%H:%M:%S%n%A, %d. %B %Y")" | $osdx
