#!/bin/sh
CLOCK=$(date "+%H:%M:%S%n%A, %d. %B %Y")
if [ -f /sys/class/power_supply/BAT0/capacity ]; then
    BATTERY="Battery: $(cat /sys/class/power_supply/BAT0/capacity)%"
else
    BATTERY=""
fi
printf '%s\n%s' "$CLOCK" "$BATTERY" | ~/scripts/screenText
