#!/bin/sh
fg1=$1
bg1=$2
fg2=$3
bg2=$4
while [ "$fg1" -ne "$fg2" ] && [ "$bg1" -ne "$bg2" ]
do
    if [ "$fg1" -lt "$fg2" ]
    then
        fg1=$(echo "obase=16; ibase=16; $fg1+1"|bc)
    fi
    if [ "$fg2" -lt "$fg1" ]
    then
        fg1=$(echo "obase=16; ibase=16; $fg1-1"|bc)
    fi
    if [ "$bg1" -lt "$bg2" ]
    then
        bg1=$(echo "obase=16; ibase=16; $bg1+1"|bc)
    fi
    if [ "$bg2" -lt "$bg1" ]
    then
        bg1=$(echo "obase=16; ibase=16; $bg1-1"|bc)
    fi
    sleep 0.1
    fg=$(printf "%06x" "$fg1")
    bg=$(printf "%06x" "$bg1")
    echo "$fg $bg"
    ./allxtermcontrol "$fg" "$bg"
done 
