#!/bin/sh

function rc {
	echo "How many fingers do you have"
	read number
	while [[ ${number} != "10" ]]
	do
		echo "Try to fly"
		echo "How many fingers do you have"
		read number
	done
}
rc
olddream
rc
file=$(~/scripts/newdream)
function phase {
	xrandr --output eDP-1 --off
	hoursstart=$(date +%H)
	minutesstart=$(date +%M)
	sleep $((2*60*60))
	hoursend=$(date +%H)
	minuteend=$(date +%M)
	printf "\n## Sleep phase $1 from ${hoursstart}:${minutesstart} to ${hoursend}:${minuteend}\n\n\n" >> ${file}
	xrandr --output eDP-1 --auto
	mpv ~/Dokumente/weakingSong.mp3
	pandoc ${file} -o ${file}
	rc
	vim + ${file}
	rc
}
phase 1
phase 2
phase 3
phase 4
