#!/bin/sh
olddream
file=$(~/scripts/newdream)
function phase {
	xrandr --output eDP-1 --off
	hoursstart=$(date +%H)
	minutesstart=$(date +%M)
	sleep $((2*60*60))
	hoursend=$(date +%H)
	minuteend=$(date +%M)
	printf "\n## Sleep phase $1 from ${hoursstart}:${minutesstart} to ${hoursend}:${minuteend}\n\n\n" >> ${file}
	xrandr --output eDP-1 --auto
	mpv ~/Dokumente/weakingSong.mp3
	pandoc ${file} -o ${file}
	vim + ${file}
}
phase 1
phase 2
phase 3
phase 4
