#!/bin/sh
if xrandr -q | grep HDMI-2 | grep -v disconnected
then
    xrandr --output eDP-1 --mode 1920x1080
    xrandr --output HDMI-2 --mode 1920x1080 --left-of eDP-1
else
    xrandr --output HDMI-2 --off
    xrandr --output eDP-1 --mode 1920x1080
fi
