#!/bin/sh
# a script to handle different links, when open from terminal with X
printf %s ${1} | xsel -b
color=$(cat ~/scripts/var/bgcolor)
function checkYoutubeStartpoint {
   if echo "${link}" | grep -e '[?#&]t=[0-9]\+s\?$' 
   then
       second=$(echo "${link}" | sed 's/.*[?#&]t=\([0-9]\+\)s\?$/\1/')
       link=$(echo "${link}" | sed 's/[?#&]t=[0-9]\+s\?$//')
       termite -e "mpv --no-osc "${link}" --start=+${second}"
   elif echo "${link}" | grep -e '[?#&]t=[0-9]\+m[0-9]\+s\?$' 
   then
       second=$(echo "${link}" | sed 's/.*[?#&]t=[0-9]\+m\([0-9]\+\)s\?$/\1/')
       minute=$(echo "${link}" | sed 's/.*[?#&]t=\([0-9]\+\)m[0-9]\+s\?$/\1/')
       link=$(echo "${link}" | sed 's/[?#&]t=[0-9]\+m[0-9]\+s\?$//')
       termite -e "mpv --no-osc "${link}" --start=+${minute}:${second}"
   else
       termite -e "mpv --no-osc "${link}""
   fi
   }
if echo "${1}" | grep -e \.mp3$ -e \.mp4$ -e \.m4v$ 
then
	termite -e "mpv --no-osc -no-audio-display ${1}"
elif echo "${1}" | grep -e m\.youtube\. 
then
        link=$(echo $1 | sed 's/m\.//' | sed 's/tube/pak/')
        checkYoutubeStartpoint 
elif echo "${1}" | grep -e youtube\. 
then
        link=$(echo $1 | sed 's/tube/pak/')
        checkYoutubeStartpoint 
elif echo "${1}" | grep -e youtu\.be
then
        link=$(echo $1 | sed 's/tu\.be\//pak.com\/watch?v=/')
        checkYoutubeStartpoint 
elif echo "${1}" | grep -e dailymotion\. -e streamable\.com -e liveleak\.com -e vimeo\.com
then
	termite -e "mpv --no-osc "${1}""
elif echo "${1}" | grep -e \.jpg$ -e \.JPG$ -e \.jpeg$ -e \.png$  -e \.PNG$
then
	if echo "${1}" | grep -e wikipedia.org # use the best quality of the picture
	then
		feh -. --image-bg $color `w3m -dump -o display_link_number=1 ${1}| grep -e \.jpg$ -e \.JPG$ -e \.jpeg$ -e \.png$ | cut -c6- | grep -v /thumb/ | grep /commons/ | grep -e ^https` || feh -. --image-bg $color "${1}"
	else
		feh -. --image-bg $color "${1}"
	fi
elif echo "${1}" | grep -e \.svg
then
	if echo "${1}" | grep -e wikipedia\.org
	then
		display `w3m -dump -o display_link_number=1 ${1} | grep -e \.svg$ | cut -c6- | grep -v /thumb/ | grep /commons/ | grep -e ^https`
	else
		display ${1}
	fi
elif echo "${1}"| grep -e \.gif -e \.gifv$
then
	mpv --loop --no-osc -no-audio-display ${1}
elif echo "${1}"| grep -e \.pdf 
then
	DIR="/tmp/newpdfs"
	if [ ! -e $DIR ]
	then
		mkdir $DIR
		chmod 0755 $DIR
	else
		rm -f $DIR/*
	fi
	DOWN="${1} -P $DIR"
	wget $DOWN
	BILD="$(echo ${1##*/})"
	zathura $DIR/$BILD 
elif echo "${1}" | grep -e imgur\.com -e flickr\.com -e i\.reddit 
then
	you-get -p "feh -. --image-bg $color" ${1}
elif echo "${1}" | grep -e gfycat.com 
then
	termite -e "mpv --loop --no-osc $(you-get -u ${1} | grep \.gif$ | head -1)"
elif echo "${1}" | grep -e www.reddit
then
	termite -e "rtv -l "${1}""
elif [[ $color == "black" ]]
then
	firefox -P DarkFirefox --new-window "${1}"
else
	firefox -P BrightFirefox --new-window "${1}"
fi
