#!/bin/sh
# keys for selection
keys=("f" "j" "d" "k" "s" "l" "a")
# get all open window names
win=($(wmctrl -l | cut -d' ' -f5))
# workspaces
ws=($(wmctrl -l | cut -d' ' -f3))
# get the pids
pids=($(wmctrl -lp | cut -d' ' -f4))
# show processes in terminal
j=1
for i in ${pids[@]}
do
	if [[ $(ps -p ${i} -o comm=) == "termite" ]]
	then
		child=$(pgrep -P ${i})
		if [[ $(ps -p ${child} -o comm=) == "zsh" ]]
		then
			child=$(pgrep -P ${child})
			win[${j}]=$(ps -p ${child} -o comm=)
		elif [[ $(ps -p ${child} -o comm=) != "" ]]
		then
			win[${j}]=$(ps -p ${child} -o comm=)
		fi
	fi
	j=$((j + 1))
done
for i in ${win[@]}
do
	echo ${i}
done
# choose the keys combinations
index=0
if [[ ${#win[@]} -gt ${#keys[@]} ]]
then
	for i in ${keys[@]}
	do
		for j in ${keys[@]}
		do
			keyComp[${index}]=${i}${j}
			index=$((index + 1))
		done
	done
else
	keyComp=${keys[@]}
fi
# get the number of windows on each workspace
declare -a workspaces=( $(for i in {1..10}; do echo 0; done) )
for i in ${ws[@]}
do
	workspaces[${i}]=$((workspaces[i]+1))
done
# generate the final lines
indexLines=0
indexWin=0
wsnumber=0
for i in ${workspaces[@]}
do
	# print the number of the workspace in the middle
	if [[  i%2 -eq 0 ]]
	then
		middle=$((i/2))
	else
		middle=$(((i+1)/2))
	fi
	for j in {0..$((i -1))}
	do
		if [[ j -eq middle ]]
		then
			lines[${index}]= "${wsnumber}|${keyComp[${indexWin}]}: ${win[${indexAbbl}]}"
		else
			lines[${index}]= " |" ${keyComp[${indexWin}]} ": " ${win[${indexAbbl}]}
		fi
		index=$((index+1))
		indexWin=$((indexAbbl+1))
	done
	# empty lines between workspaces
	lines[${index}]=""
	index=$((index+1))
	wsnumber=$((wsnumber+1))
done

