#!/bin/sh
year=$(date +"%Y" -d "4 hours ago")
month=$(date +"%m" -d "4 hours ago")
day=$(date +"%d" -d "4 hours ago")
if [ ${month} == "01" ]; then
	monthname=1_Januar
elif [ ${month} == "02" ]; then
	monthname=2_Februar
elif [ ${month} == "03" ]; then
	monthname=3_Maerz
elif [ ${month} == "04" ]; then
	monthname=4_April
elif [ ${month} == "05" ]; then
	monthname=5_Mai
elif [ ${month} == "06" ]; then
	monthname=6_Juni
elif [ ${month} == "07" ]; then
	monthname=7_Juli
elif [ ${month} == "08" ]; then
	monthname=8_August
elif [ ${month} == "09" ]; then
	monthname=9_September
elif [ ${month} == "10" ]; then
	monthname=10_Oktober
elif [ ${month} == "11" ]; then
	monthname=11_November
elif [ ${month} == "12" ]; then
	monthname=12_Dezember
fi
mkdir -p ~/Dokumente/Traeume/${year}/${monthname}
printf "# Traeume vom ${day}.${month}.${year}\n\n\n" >> ~/Dokumente/Traeume/${year}/${monthname}/Traeume_vom_${day}.${month}.${year}.md
echo ~/Dokumente/Traeume/${year}/${monthname}/Traeume_vom_${day}.${month}.${year}.md
