#!/bin/sh
if [ $(date +"%m") == "01" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/1_Januar
   echo "~/Dokumente/Traeume/$(date +"%Y")/1_Januar/Traeume_vom_$(date +"%d").01.$(date +"%Y").md"
elif [ $(date +"%m") == "02" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/2_Februar
   echo "~/Dokumente/Traeume/$(date +"%Y")/2_Februar/Traeume_vom_$(date +"%d").02.$(date +"%Y").md"
elif [ $(date +"%m") == "03" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/3_Maerz
   echo "~/Dokumente/Traeume/$(date +"%Y")/3_Maerz/Traeume_vom_$(date +"%d").03.$(date +"%Y").md"
elif [ $(date +"%m") == "04" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/4_April
   echo "~/Dokumente/Traeume/$(date +"%Y")/4_April/Traeume_vom_$(date +"%d").04.$(date +"%Y").md"
elif [ $(date +"%m") == "05" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/5_Mai
   echo "~/Dokumente/Traeume/$(date +"%Y")/5_Mai/Traeume_vom_$(date +"%d").05.$(date +"%Y").md"
elif [ $(date +"%m") == "06" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/6_Juni
   echo "~/Dokumente/Traeume/$(date +"%Y")/6_Juni/Traeume_vom_$(date +"%d").06.$(date +"%Y").md"
elif [ $(date +"%m") == "07" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/7_Juli
   echo "~/Dokumente/Traeume/$(date +"%Y")/7_Juli/Traeume_vom_$(date +"%d").07.$(date +"%Y").md"
elif [ $(date +"%m") == "08" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/8_August
   echo "~/Dokumente/Traeume/$(date +"%Y")/8_August/Traeume_vom_$(date +"%d").08.$(date +"%Y").md"
elif [ $(date +"%m") == "09" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/9_September
   echo "~/Dokumente/Traeume/$(date +"%Y")/9_September/Traeume_vom_$(date +"%d").09.$(date +"%Y").md"
elif [ $(date +"%m") == "10" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/10_Oktober
   echo "~/Dokumente/Traeume/$(date +"%Y")/10_Oktober/Traeume_vom_$(date +"%d").10.$(date +"%Y").md"
elif [ $(date +"%m") == "11" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/11_November
   echo "~/Dokumente/Traeume/$(date +"%Y")/11_November/Traeume_vom_$(date +"%d").11.$(date +"%Y").md"
elif [ $(date +"%m") == "12" ]; then
   mkdir -p ~/Dokumente/Traeume/$(date +"%Y")/12_Dezember
   echo "~/Dokumente/Traeume/$(date +"%Y")/12_Dezember/Traeume_vom_$(date +"%d").12.$(date +"%Y").md"
fi
