#!/bin/bash
# I don't need this. calcurse has that function by itself.
#format: month/day/year hour:minute monthend:dayend:yearend
minute=$(echo $2 | cut -d: -f2)
hour=$(echo $2 | cut -d: -f1)
day=$(echo $1 | cut -d/ -f2)
month=$(echo $1 | cut -d/ -f1)
year=$(echo $1 | cut -d/ -f3)
minuteend=$(echo $4 | cut -d: -f2)
hourend=$(echo $4 | cut -d: -f1)
dayend=$(echo $3 | cut -d/ -f2)
monthend=$(echo $3 | cut -d/ -f1)
yearend=$(echo $3 | cut -d/ -f3)
desc=$5
if ps -au | grep calcurse | grep -v grep
then
	echo "please close calcurse, before using this script"
elif [[ $month -gt 12 || 1 -gt $month || $day -gt 31 || 1 -gt $day || $hour -gt 24 || 0 -gt $hour || $minute -gt 59 || 0 -gt $minute ]]
then
	echo "not a correct time, format: month/day/year hour:minute monthend:dayend:yearend description"
elif [[ ( $month -eq 2 && $day -gt 28 )||(( $month -eq 4 || $month -eq 6 || $month -eq 9 || $month -eq 11 )&& $day -gt 30 ) ]]
then
	echo "not a correct time, format: month/day/year hour:minute monthend:dayend:yearend description"
elif [[ $monthend -gt 12 || 1 -gt $monthend || $dayend -gt 31 || 1 -gt $dayend || $hourend -gt 24 || 0 -gt $hourend || $minuteend -gt 59 || 0 -gt $minuteend ]]
then
	echo "not a correct time, format: month/day/year hour:minute monthend:dayend:yearend description"
elif [[ ( $monthend -eq 2 && $dayend -gt 28 )||(( $monthend -eq 4 || $monthend -eq 6 || $monthend -eq 9 || $monthend -eq 11 )&& $dayend -gt 30 ) ]]
then
	echo "not a correct time, format: month/day/year hour:minute monthend:dayend:yearend description"
elif [[ $year -lt $(date +%Y) ||( $year -eq $(date +%Y) &&( $month -lt $(date +%m) ||( $month -eq $(date +%m) &&( $day -lt $(date +%d) \
	||( $day -eq $(date +%d) &&( $hour -lt $(date +%H) ||( $hour -eq $(date +%H) && $minute -le $(date +%m) ))))))) ]]
then
	echo "time is in the past, format: month/day/year hour:minute monthend:dayend:yearend description"
else
	while [[ $year -lt $yearend || ( $year -le $yearend  && ( $month -lt $monthend || ( $month -eq $monthend &&  $day -le $dayend ))) ]]
	do
		echo "$month/$day/$year @ $hour:$minute -> $month/$day/$year @ $hourend:$minuteend|$desc">> ~/.calcurse/apts
		if [[ $(expr $day + 7) -le  28 ]]
		then
			day=$(expr $day + 7)
		elif [[ $(expr $day + 7) -le 30 && $month -ne 2 ]]
		then
			day=$(expr $day + 7)
		elif [[ $(expr $day + 7) -le 31 && $month -ne 2 && $month -ne 4 && $month -ne 6 && $month -ne 9 && $month -ne 11 ]]
		then
			day=$(expr $day + 7)
		elif [[ $month -ne 12 ]]
		then
			if [[ $month -eq 2 ]]
			then
				day=$(expr $day - 21)
			elif [[ $month -ne 2 && $month -ne 4 && $month -ne 6 && $month -ne 9 && $month -ne 11 ]]
			then
				day=$(expr $day - 24)
			else
				day=$(expr $day - 23)
			fi
			month=$(expr $month + 1)
		else
			year=$(expr $year + 1)
			month=1
			day=$(expr $day - 24)
		fi
	done
fi
