#!/bin/bash
qemu-system-x86_64 \
		-enable-kvm \
		-m 12288 \
		-cpu host \
		-smp sockets=1,cores=4,threads=1 \
		-net nic -net bridge,br=br0\
		-device vfio-pci,host=06:00.0,x-vga=on \
		-device vfio-pci,host=06:00.1 \
		-vga none \
		-monitor stdio\
		-device virtio-scsi-pci,id=scsi \
		-drive file=~/kvm/en_windows_10_education_version_1511_x64_dvd_7223856.iso,id=isocd,format=raw,if=none -device scsi-cd,drive=isocd \
		-drive file=~/kvm/virtio-win-0.1.126.iso,id=virtiocd,if=none,format=raw -device ide-cd,bus=ide.1,drive=virtiocd \
		-drive file=/dev/sdb,id=ssd,format=raw,if=none -device scsi-hd,drive=ssd  \
		-drive file=/dev/sdc,id=disk,format=raw,if=none -device scsi-hd,drive=disk 
echo "1" > /var/local/hddoff
